### ISSUE TITLE
I want to play around and possibly contribute to this project, but I cannot manage to properly compile it

### ISSUE THREAD

**Issue by Hamunii** [klepticat/JetpackWarning#1]
I don't really know much about C# and stuff, but anyways when I try to compile the project (Visual Studio Code, Ctrl+Shift+P >.NET: Build), it won't build. Is the project missing some configuration files? Thanks

Basically I would just like to play around with using the jetpackPower, as I think it's almost more important than forces.magnitude for trying not to explode and still maintaining high speed

**Comment by klepticat** [comment]
You'll need to grab the assemblies from the game files yourself but I can upload everything else required for a build.

**Comment by klepticat** [comment]
c17ee430d2c947d5704fe6bcf2271001d7a013b2 Should be all you need to build other than the assemblies.
